// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Domain struct {
	DomainID        int64
	UserID          uuid.UUID
	Name            string
	ScannedAt       sql.NullTime
	CountSubdomains int32
}

type DomainOpenPort struct {
	DomainID   int64
	OpenPortID int64
	CreatedAt  time.Time
}

type OpenPort struct {
	OpenPortID      int64
	Port            int32
	ServiceName     string
	ServiceVersion  string
	OperatingSystem string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Subdomain struct {
	SubdomainID int64
	DomainID    int64
	Name        string
	StatusCode  int32
	TitlePage   string
	Ip          string
	IsAlive     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type SubdomainTechnology struct {
	SubdomainID  int64
	TechnologyID int64
}

type Technology struct {
	TechnologyID int64
	Name         string
	Version      string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
