// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: open_ports.sql

package dbsqlc

import (
	"context"
)

const linkDomainOpenPort = `-- name: LinkDomainOpenPort :exec
INSERT INTO domain_open_ports (
    domain_id,
    open_port_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (domain_id, open_port_id) DO NOTHING
`

type LinkDomainOpenPortParams struct {
	DomainID   int64
	OpenPortID int64
}

func (q *Queries) LinkDomainOpenPort(ctx context.Context, arg LinkDomainOpenPortParams) error {
	_, err := q.db.ExecContext(ctx, linkDomainOpenPort, arg.DomainID, arg.OpenPortID)
	return err
}

const upsertOpenPort = `-- name: UpsertOpenPort :one
INSERT INTO open_ports (
    port,
    service_name,
    service_version,
    operating_system
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (port, service_name, service_version, operating_system) DO UPDATE
SET updated_at = NOW()
RETURNING open_port_id
`

type UpsertOpenPortParams struct {
	Port            int32
	ServiceName     string
	ServiceVersion  string
	OperatingSystem string
}

func (q *Queries) UpsertOpenPort(ctx context.Context, arg UpsertOpenPortParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertOpenPort,
		arg.Port,
		arg.ServiceName,
		arg.ServiceVersion,
		arg.OperatingSystem,
	)
	var openPortID int64
	err := row.Scan(&openPortID)
	return openPortID, err
}
