// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	LinkSubdomainTechnology(ctx context.Context, arg LinkSubdomainTechnologyParams) error
	RefreshDomainScanStats(ctx context.Context, arg RefreshDomainScanStatsParams) error
	UpsertDomain(ctx context.Context, arg UpsertDomainParams) (int64, error)
	UpsertSubdomain(ctx context.Context, arg UpsertSubdomainParams) (int64, error)
	UpsertTechnology(ctx context.Context, arg UpsertTechnologyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
