// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scan_subdomain.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const linkSubdomainTechnology = `-- name: LinkSubdomainTechnology :exec
INSERT INTO subdomain_technologies (
    subdomain_id,
    technology_id
) VALUES (
    $1,
    $2
)
ON CONFLICT (subdomain_id, technology_id) DO NOTHING
`

type LinkSubdomainTechnologyParams struct {
	SubdomainID  int64
	TechnologyID int64
}

func (q *Queries) LinkSubdomainTechnology(ctx context.Context, arg LinkSubdomainTechnologyParams) error {
	_, err := q.db.ExecContext(ctx, linkSubdomainTechnology, arg.SubdomainID, arg.TechnologyID)
	return err
}

const refreshDomainScanStats = `-- name: RefreshDomainScanStats :exec
UPDATE domains
SET scanned_at = $2,
    count_subdomains = (
        SELECT COUNT(*)
        FROM subdomains
        WHERE subdomains.domain_id = $1
    )
WHERE domains.domain_id = $1
`

type RefreshDomainScanStatsParams struct {
	DomainID  int64
	ScannedAt sql.NullTime
}

func (q *Queries) RefreshDomainScanStats(ctx context.Context, arg RefreshDomainScanStatsParams) error {
	_, err := q.db.ExecContext(ctx, refreshDomainScanStats, arg.DomainID, arg.ScannedAt)
	return err
}

const upsertDomain = `-- name: UpsertDomain :one
INSERT INTO domains (
    user_id,
    name,
    scanned_at,
    count_subdomains
) VALUES (
    $1,
    $2,
    $3,
    0
)
ON CONFLICT (user_id, name) DO UPDATE
SET scanned_at = EXCLUDED.scanned_at
RETURNING domain_id
`

type UpsertDomainParams struct {
	UserID    uuid.UUID
	Name      string
	ScannedAt sql.NullTime
}

func (q *Queries) UpsertDomain(ctx context.Context, arg UpsertDomainParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDomain, arg.UserID, arg.Name, arg.ScannedAt)
	var domain_id int64
	err := row.Scan(&domain_id)
	return domain_id, err
}

const upsertSubdomain = `-- name: UpsertSubdomain :one
INSERT INTO subdomains (
    domain_id,
    name,
    status_code,
    title_page,
    ip,
    is_alive
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (domain_id, name) DO UPDATE
SET status_code = EXCLUDED.status_code,
    title_page = EXCLUDED.title_page,
    ip = EXCLUDED.ip,
    is_alive = EXCLUDED.is_alive,
    updated_at = NOW()
RETURNING subdomain_id
`

type UpsertSubdomainParams struct {
	DomainID   int64
	Name       string
	StatusCode int32
	TitlePage  string
	Ip         string
	IsAlive    bool
}

func (q *Queries) UpsertSubdomain(ctx context.Context, arg UpsertSubdomainParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertSubdomain,
		arg.DomainID,
		arg.Name,
		arg.StatusCode,
		arg.TitlePage,
		arg.Ip,
		arg.IsAlive,
	)
	var subdomain_id int64
	err := row.Scan(&subdomain_id)
	return subdomain_id, err
}

const upsertTechnology = `-- name: UpsertTechnology :one
INSERT INTO technologies (
    name,
    version
) VALUES (
    $1,
    $2
)
ON CONFLICT (name, version) DO UPDATE
SET updated_at = NOW()
RETURNING technology_id
`

type UpsertTechnologyParams struct {
	Name    string
	Version string
}

func (q *Queries) UpsertTechnology(ctx context.Context, arg UpsertTechnologyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTechnology, arg.Name, arg.Version)
	var technology_id int64
	err := row.Scan(&technology_id)
	return technology_id, err
}
