package service

import (
	"context"
	users "go-server/gen/user"
)

// server implements the UserServiceServer interface generated by protoc.
// We use a lowercase name to keep the struct private to this package.
type server struct {
	// We embed UnimplementedUserServiceServer to ensure our struct
	// satisfies the interface even if we add new methods to the .proto file later.
	users.UnimplementedUserServiceServer
}

// NewUserServer returns a new UserService gRPC handler.
func NewUserServer() users.UserServiceServer {
	return &server{}
}

// GetUser handles the incoming gRPC request for a single user.
// req: The data sent by the FastAPI client (contains UserId).
// res: The data we send back (Name and Email).
func (s *server) GetUser(ctx context.Context, req *users.UserRequest) (*users.UserResponse, error) {
	// This is a placeholder response until user storage is wired in.
	return &users.UserResponse{
		Name:  "Koko",
		Email: "koko@gmail.com",
	}, nil
}
