package service

import (
	"context"

	users "go-server/gen/user"
)

// server implements the UserServiceServer interface generated by protoc.
// We use a lowercase name to keep the struct private to this package.
type server struct {
	// We embed UnimplementedUserServiceServer to ensure our struct
	// satisfies the interface even if we add new methods to the .proto file later.
	users.UnimplementedUserServiceServer
}

// NewServer is a constructor function that returns a new instance of our gRPC server.
func NewUserServer() users.UserServiceServer {
	return &server{}
}

// GetUser handles the incoming gRPC request for a single user.
// req: The data sent by the FastAPI client (contains UserId).
// res: The data we send back (Name and Email).
func (s *server) GetUser(ctx context.Context, req *users.UserRequest) (*users.UserResponse, error) {
	// Current logic: Returns a hardcoded response.
	// Future logic: This is where we would call our Database/Repository layer.
	return &users.UserResponse{
		Name:  "Koko",
		Email: "koko@gmail.com",
	}, nil
}
